# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: local
    hooks:
      - id: talisman-commit
        name: talisman
        entry: talisman --githook pre-commit
        stages: [commit]
        # talisman currently discovers files by itself and does not take them on the cli
        pass_filenames: false
        types: [text]
        language: golang
